name: Android Test and Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up secret Key
        shell: bash
        env:
          SECRETS_XML: ${{secrets.SECRETS_XML}}
        run: |
          touch app/src/main/res/values/secrets.xml
          echo $SECRETS_XML > app/src/main/res/values/secrets.xml

      - name: Build Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test

